### ISSUE TITLE
TrxDate seems to be in a local time which makes it difficult to convert to our local time

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#10]
The TrxDate we get back from a transaction response seems to be in the local time of the remote endpoint rather than UTC. This makes it impossible for us to convert that date/time to our local timezone format.

Ex: We (in Central timezone) see the date as 2:00 PM when it is 4:00 PM our time.

**Comment by nikkipnguyen** [comment]
Hello there,
Thank you for the kind feedback. All existing transaction date/time is currently in Pacific time zone. We understand the challenge from conversion in compared to UTC. We'll make a note of this for future consideration.
