### ISSUE TITLE
User defined values not coming back as part of transactions

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#11]
When we create a transaction in Payfabric we are setting one of the user defined fields to a value. When we later get that transaction back the user defined fields are all blank. This limits the usefulness of the user defined fields.

**Comment by nikkipnguyen** [comment]
Hello there,

We're able to see the UserDefined values coming back from our GET API by Transaction Key testing. Could you help provide the API version as well as get transaction method you're using when you experienced this issue? Thank you.

**Comment by CoolDadTx** [comment]
Creating the transaction:
URL: https://sandbox.payfabric.com/payment/api/transaction/create
Request:
```
{   
   "SetupId": "xyz",
   "Amount":210.0000,
   "BatchNumber":null,
   "Currency":"USD",
   "Customer":"214287443",
   "Tender": "CreditCard",
   "TrxUserDefined1":"1_58010",
   "TrxUserDefined2":null,
   "TrxUserDefined3":null,
   "TrxUserDefined4":null,
   "Type": "Book"
}
```

Getting the transaction:
URL: https://sandbox.payfabric.com/payment/api/transaction/180329092979
Response:
```
"Card":{
   ...
   "UserDefine1":"",
   "UserDefine2":"",
   "UserDefine3":"",
   "UserDefine4":""
},
"TrxResponse":{
   ...
  "Message":"Approved",
  "OriginationID":"A70AA89E4CB8",
  "Status":"Approved",
   "TrxDate":"3\/29\/2018 9:17:15 AM",
   "TrxKey":"180329092979"
 },
 "TrxUserDefine1":"",
 "TrxUserDefine2":"",
 "TrxUserDefine3":"",
 "TrxUserDefine4":"",
 "Type":"Book"
}
```

**Comment by nikkipnguyen** [comment]
Hello,
Thank you for sending the snippet through. Could you help remove the 'd' from your 'TrxUserDefine**d**1' and retry from your end? Sorry, it should be: TrxUserDefined.

**Comment by CoolDadTx** [comment]
That was it. I was using TrxUserDefined1 instead of TrxUserDefine1. Thanks.
