### ISSUE TITLE
User defined fields are lost when changing a Book request to a Ship request

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#12]
We are doing a pre-auth (Book) request using the hosted page. When the call returns we are getting our user defined values back in the TrxUserDefinedX fields. We then do some processing on our side and try to capture the payment by using the ?trxtype=SHIP endpoint on the Book transaction. When processing completes we get a brand new transaction back. But the new transaction has thrown away all the user-defined fields so we lose the data we had stored.

This may be by design but it introduces problems. Without the user defined data we cannot link the transaction back to our data. Our original plan was to store a unique identifier in these fields that will work its way to the backend processor such that when we got our monthly report from them we have something to compare against our side of the fence for reconciliation like we do in our existing payment system. But without the user defined fields that doesn't seem possible.

**Comment by nikkipnguyen** [comment]
Hello,
You are right. We currently do not copy across the TrxUserDefine1-4 fields across. However, we do copy across the Document.UserDefined array of key value pairs. Could you give this a try to see if it'll achieve what you need?
I also want to clarify the "backend processor" referenced in your post. Is this a payment processor you're referring to or a different system/application? Kindly note, we currently do not pass these userdefined [document/trx] fields to payment gateway/processor. If you expect these data to get to the gateway/processor backend, then we'd need to pass it into a specific field [existed on the payment gateway], depending on the gateway provider.

**Comment by CoolDadTx** [comment]
Yes, we need to send data to the gateway so they will provide that data back when they send us monthly reconciliation reports. Where is the documentation that specifies what fields are passed to a specific gateway provider (i.e. Chase)?

**Comment by JingjingHu** [comment]
Hi,
It is not available in public, could you provide your Email address, we will send specific gateway fields mapping to you.

**Comment by CoolDadTx** [comment]
mtaylor at FSMB dot org

**Comment by CoolDadTx** [comment]
I provided my email but didn't get anything. Have you sent me this document yet?

**Comment by JingjingHu** [comment]
Please check your inbox, I have sent it out.

**Comment by CoolDadTx** [comment]
I got it, thank you.
