### ISSUE TITLE
Resolution of the TransactionKey value

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#13]
It appears that in the sandbox the transaction key is simply the date/time (yyMMddhhmmss). Does this mean that I can only generate 1 transaction request per second? What if I have multiple applications running simultaneously and they happen to try to create a transaction at the same time. Will I get potentially duplicate keys?

**Comment by JingjingHu** [comment]
Hi,
That's a coincidence, transaction key is not related to date/time, the transaction key will increase in sequence. the key won't be duplicated.

**Comment by CoolDadTx** [comment]
Thank you for the clarification.
