### ISSUE TITLE
Missing instructions for partial shipments

### ISSUE THREAD

**Issue by aesther2** [PayFabric/APIs#15]
Need to document how to take an book transaction and do a partial capture "ship" of the amount. Then what do to do capture the remainder for a second shipment.

**Comment by JingjingHu** [comment]
Thanks for your question, how to take an book transaction you can refer to this link 'https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Transactions.md#create-and-process-a-transaction', just need to Set the 'Type' in the request body to 'Book'. if you want to capture amount other than authorized amount, you can use the same API call /transaction/process with below request body, The 'ReferenceKey' is the 'TrxKey' of the book transaction, and 'capture a different amount with authorized amount' also depends on which gateway you are using, for instance, some gateways Do NOT support capture with higher amount than authorized amount. However, an book transaction is NOT allowed to be captured multiple times. Let me know if you have any further questions.

{
  "Amount": "2",
  "Type": "Ship",
  "ReferenceKey": "18111800213042"
}

**Comment by navarr** [comment]
@JingjingHu Many times a merchant will want to capture part of the transaction, and then later capture the rest.  Is this not possible using PayFabric's APIs?

**Comment by JingjingHu** [comment]
@navarr yes, PayFabric API /transaction/process support that as long as the gateway the merchant is using support multiple captures. please refer to above my comment about /transaction/process (https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Transactions.md#create-and-process-a-transaction) how to capture the book, you are able to capture the same book multiple times with the same request.

**Comment by aesther2** [comment]
JungjingHu, I found that was not true when I attempted it some months ago. I found that once an authorization is captured you have to generate a new authorization. It might be gateway specific.


Andrew Esther
616.954.6691 x107

**Comment by JingjingHu** [comment]
It is gateway specific, you can try USAePaySOAP.

**Comment by aesther2** [comment]
That’s not helpful to my clients though. My app is supposed to handle ANY gateway, and split shipments are just a normal thing to need to support.


Andrew Esther
616.954.6691 x107

**Comment by navarr** [comment]
I performed some more research on this last night and it's what the
gateways themselves support, not Payfabric

In some cases the gateways only support what the banks support

As an example, Auth.net can handle partials but most banks can't

**Comment by aesther2** [comment]
I would appreciate if that was documented in some way. It should be mentioned in the API docs whether you can capture on authorizations multiple times or not. It should also be mentioned how to get authorizations from other transactions. This really needs to be a straightforward process as split shipments are common and I need to let clients know what gateways will work or won’t work.


Andrew Esther
616.954.6691 x107

**Comment by JingjingHu** [comment]
Thanks for your feedback, those are good suggestions, we will update it accordingly.
