### ISSUE TITLE
Authorization document shows basic auth but it is either incorrect or doesn't work

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#20]
Because we are using `AuthenticationHeaderValue` from .NET to authenticate to PayFabric we wanted to use basic auth. The documentation says it should work but it doesn't. I tried in Postman as well.

However the documentation shows 2 different values being used so I'm unclear if there is an issue with the API or the documentation is wrong. In the comments about basic auth it says the format is `{DCN}{DeviceId}:{Password}` but it doesn't define what `DCN` is. However in the code example it just uses the device ID and password as I would expect. However trying to do this in Postman generates a 401. I know the info is correct because if I switch over to using the other auth approach it works correctly.

**Comment by CoolDadTx** [comment]
I think I figured out what was meant and I'm able to get basic working now. I think it should be made more clear though. In most cases the API is called with the format `{dcn}:{deviceid}` but for basic auth the format is `{dcn}{deviceid}` without the colon. The docs mention that this is for cases where a header cannot have a colon but what is confusing is that this value is separated from the password by a colon. So I think the comment about the colon was probably referring to the DCN thing but it isn't clear.

**Comment by JingjingHu** [comment]
Thanks for your comments, we have updated the documentation to make it more clear.
