### ISSUE TITLE
Transaction Response Status -- What is More info 

### ISSUE THREAD

**Issue by armins88** [PayFabric/APIs#21]
Can I assume the transaction was successfully processed if the transaction status is "More Info"?
I am referring to https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Objects.md#transaction-response

Thank you

**Comment by JingjingHu** [comment]
Thanks for your question. The answer is no, transaction is processed successfully must be Approved. 'More Info' means some required fields are missing for specific gateway.
