### ISSUE TITLE
Missing Functionality/Documentation

### ISSUE THREAD

**Issue by dominichartjes** [PayFabric/APIs#30]
Hello,

We would like to use the PaymentProfileId created on a hosted PayFabric wallet management page as an argument to the CreateTransaction and ProcessTransaction API endpoints. We had designed our solution in this way to avoid needing to handle Account Numbers and ABA numbers in our server side code. The other consideration is that our invoice payment code runs via windows service so we cannot use a hosted payment page.

**Comment by JingjingHu** [comment]
Hi,
We do support the scenario, once you created a wallet on hosted PayFabric wallet page, you can use retrieve credit card API to get the wallet's ID (Refer to https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Wallets.md#retrieve-credit-cards--echecks), and then use the wallet/card ID to create/process a transaction (Refer to https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Transactions.md#create-and-process-a-transaction). Please let me know if you have any questions. thanks.

**Comment by dominichartjes** [comment]
Hello, and thank you for getting back to me. I have reviewed these documents but still am having difficulty with this scenario. I've attached a postman collection so you can run my work on your own instance if you like. Once downloaded, you will need to change the extension from .txt to .json in order to import it into Postman.

Here is my query to retrieve a Wallet ID: `GET /wallet/getbycustomer?customer=97285&tender=echeck`

I get two wallets as a result. The first has ID e0cf1bdb-147d-487c-8a43-312dd88eefb3. Where in the transaction/create schema can I pass the wallet ID?

[PayFabric API.postman_collection.txt](https://github.com/PayFabric/APIs/files/6509960/PayFabric.API.postman_collection.txt)

**Comment by dominichartjes** [comment]
Just to make sure the whole conversation is available, I'm copying in the question and response that Auer Steel got when asking about this same problem.

### My initial question:
 
Briefly, the issue has to do with what I think is a limitation in the Transaction Creation/Processing APIs. Our workflow involves capturing a customer's ACH info via the PayFabric Hosted Wallet page and then using the generated PaymentProfileId to perform the processing of the transaction during the Auersteel: Process Payments job. Unfortunately, neither the Create and Process a Transaction nor the Process an eCheck Transaction APIs include a PaymentProfileId in their schema. The implication of making the Wallet and Payment functionalities accessible via API is that we could use the generated wallets for creating and processing payments, but this is either not possible at present, or it is missing from the documentation.

### Response from PayFabric to Auer Steel:

I’d like to direct you to the JSON Objects for PayFabric: https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Objects.md#transaction.
Card Data: https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Objects.md#card

I believe what you are looking for is not the PaymentProfileId, but instead the Customer (Customer ID) field. This object allows you to reference the saved wallet data (CC and ACH).
The example request on the Create an eCheck Transaction page displays the Customer as follows:
	"Customer": "JOHNDOE0001"
	Where JOHNDOE0001 is the reference to the saved data in the wallet.

### Questions I still have after that explanation:

I've tried creating a transaction using this concept but am still not having any success. Are you saying that I should be sending the Wallet Id in the Customer field instead of the customer id? If a customer has more than one wallet, how would I indicate which wallet to use? I have tried a number of different request bodies but none have resulted in the desired behavior. I'm expecting that when I create a transaction referencing the wallet I would like to use, I should see the masked version of that wallet's "account" and "ABA" number when I query the transaction with `GET /transaction/{{key}}`

Thanks for your attention to this matter.

Best,
Dominic

**Comment by dominichartjes** [comment]
I've made updates to the postman collection. Please disregard previous collection if it was already downloaded.
[PayFabric API.postman_collection.txt](https://github.com/PayFabric/APIs/files/6510319/PayFabric.API.postman_collection.txt)

**Comment by dominichartjes** [comment]
### This email helped me connect the dots:

What do you mean by PaymentProfileID? I don’t recognize that as a field PayFabric creates.

This link shows an example on how to use an existing stored wallet during the Process Transaction endpoint.
https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Transactions.md#create-and-process-a-transaction

Here are a few more links to create wallet either from API or Hosted Wallet Page, we highly recommend using a hosted wallet page to create wallet for security, and get the wallet ID through Wallet Retrieve API call.

### Summary

The ID in `{ "Card": { "ID":  "GUID" }}` is where you pass the Wallet ID that was retrieved from the Wallet endpoint. Please update documentation to explicitly call out the connection between Card ID and Wallet ID.

**Comment by nikkipnguyen** [comment]
Thank you for your suggestion. The definition and description for ID under Card object has been updated for better clarity.

**Comment by dominichartjes** [comment]
That is excellent! Thanks again for your help.
________________________________
