### ISSUE TITLE
L2/L3 field documentation is unclear

### ISSUE THREAD

**Issue by mtaylorfsmb** [PayFabric/APIs#46]
In the L2/L3 field documentation [here](https://github.com/PayFabric/APIs/blob/master/PayFabric/Sections/Level%202%20and%20Level%203%20Fields.md) the documentation is unclear on some things.

## Commodity Code

It mentions that the commodity code is required and that you should refer to the documentation to the right to get the right one for your industry. But there is no actual list given anywhere. Please link to or provide a list of commodity codes that should be used. 

Also please consider clarifying whether this is a fixed list that is validated or simply a required field.

## Required fields do not line up with UI

In the Gateway Profile UI where you enable L2/L3 fields it provides a list of required fields (and some optional ones) and the tooltip has some basic information. But the UI doesn't line up with the required fields in the docs. For example freight amount is listed as required in the docs but not exposed in the UI. Shipping country is in the UI as required but not listed in the docs. It is unclear whether the documentation is up to date with the UI or not.

**Comment by JingjingHu** [comment]
Thanks for your questions. We have updated the Level 2 and Level 3 fields page up to date. For the required fields in the UI, I'm assuming you are referring to default L2/3 fields of gateway accounts, not all of the fields in the UI are required, we will update it in the future release. Thanks again.
