### ISSUE TITLE
URLs are inconsistently documented

### ISSUE THREAD

**Issue by CoolDadTx** [PayFabric/APIs#9]
The base URLs are inconsistently defined. Given the resource URL for creating token creation - {baseUrl}/token/create -

On the readme pages it says to use https://sandbox.payfabric.com/payment/api. This generates a 401 even though the credentials appear correct.

In the C# samples it uses https://sandbox.payfabric.com/v3/Payfabric/rest/api. This generates a 404.

In the Java samples it uses https://sandbox.payfabric.com/rest/v1/api. Didn't try this URL.

**Comment by JingjingHu** [comment]
Thanks for your feedback, this issue have been addressed. URL https://sandbox.payfabric.com/payment/api is the right one, there have three versions of API, this URL is for V3, please make sure you are using the right version of credentials aginst the URL.
